import io
from PIL import Image, ImageDraw, ImageFont

def generate_pnl_card(token_symbol: str, pnl_pct: float, pnl_usd: float) -> io.BytesIO:
    """Generates a beautiful PnL flex card in memory."""
    width, height = 800, 400
    
    # Create dark background
    img = Image.new("RGB", (width, height), color="#121212")
    draw = ImageDraw.Draw(img)
    
    # Try to load a nice font, fallback to default with size
    try:
        font_title = ImageFont.load_default(size=48)
        font_pnl = ImageFont.load_default(size=120)
        font_sub = ImageFont.load_default(size=36)
        font_watermark = ImageFont.load_default(size=24)
    except TypeError:
        # For older Pillow versions
        font_title = ImageFont.load_default()
        font_pnl = ImageFont.load_default()
        font_sub = ImageFont.load_default()
        font_watermark = ImageFont.load_default()

    # Colors
    is_profit = pnl_pct >= 0
    accent_color = "#00FF00" if is_profit else "#FF3333"
    
    # Draw border accent
    draw.rectangle([0, 0, width-1, 10], fill=accent_color)
    
    # Draw Title
    title = f"{token_symbol.upper()} Position"
    draw.text((40, 50), title, font=font_title, fill="#FFFFFF")
    
    # Draw PnL Percentage
    pnl_text = f"+{pnl_pct:.2f}%" if is_profit else f"{pnl_pct:.2f}%"
    draw.text((40, 120), pnl_text, font=font_pnl, fill=accent_color)
    
    # Draw PnL USD
    usd_text = f"Profit: +${pnl_usd:,.2f}" if is_profit else f"Loss: -${abs(pnl_usd):,.2f}"
    draw.text((45, 260), usd_text, font=font_sub, fill="#BBBBBB")
    
    # Draw Watermark
    watermark = "⚡ Generated by Zenith Crypto PRO"
    draw.text((width - 450, height - 45), watermark, font=font_watermark, fill="#555555")
    
    # Draw subtle background shapes (simulating a chart)
    points = []
    if is_profit:
        points = [(400, 300), (500, 250), (600, 280), (700, 150), (800, 50)]
    else:
        points = [(400, 100), (500, 150), (600, 120), (700, 250), (800, 350)]
        
    for i in range(len(points)-1):
        draw.line([points[i], points[i+1]], fill=accent_color, width=4)
        
    # Export to bytes
    bio = io.BytesIO()
    img.save(bio, format="PNG")
    bio.seek(0)
    return bio
