"""sync_models

Revision ID: b7c1b7afc41a
Revises: 95c30b455564
Create Date: 2026-07-19 02:28:37.723925

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7c1b7afc41a"
down_revision: str | Sequence[str] | None = "95c30b455564"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("admin_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "KEYGEN",
                "KEYGEN_BULK",
                "EXTEND",
                "REVOKE",
                "BROADCAST",
                "USER_LOOKUP",
                "USER_SEARCH",
                "GROUP_LOOKUP",
                "TICKET_REPLY",
                "TICKET_CLOSE",
                "FAQ_ADD",
                "FAQ_DELETE",
                "CANNED_ADD",
                "CANNED_DELETE",
                "BROADCAST_SCHEDULED",
                "GROUP_DISABLE",
                "BOT_REGISTER",
                "BOT_UNREGISTER",
                name="actiontype",
            ),
            nullable=False,
        ),
        sa.Column("target_user_id", sa.BigInteger(), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bot_registry",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_name", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", "ERROR", name="botstatus"), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_health_check", sa.DateTime(timezone=True), nullable=True),
        sa.Column("health_status", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("bot_name"),
    )
    op.create_table(
        "crypto_activation_keys",
        sa.Column("key_string", sa.String(length=50), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=True),
        sa.Column("used_by", sa.BigInteger(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("key_string"),
    )
    op.create_table(
        "crypto_price_alerts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_id", sa.String(length=100), nullable=False),
        sa.Column("token_symbol", sa.String(length=20), nullable=False),
        sa.Column("target_price", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("is_triggered", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_crypto_price_alerts_user_id"), "crypto_price_alerts", ["user_id"], unique=False)
    op.create_table(
        "crypto_saved_audits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("contract", sa.String(length=150), nullable=False),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "contract", name="uix_user_contract"),
    )
    op.create_index(op.f("ix_crypto_saved_audits_user_id"), "crypto_saved_audits", ["user_id"], unique=False)
    op.create_table(
        "crypto_subscriptions",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "crypto_tracked_wallets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("wallet_address", sa.String(length=100), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=True),
        sa.Column("last_checked_tx", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "wallet_address", name="uix_user_wallet"),
    )
    op.create_index(op.f("ix_crypto_tracked_wallets_user_id"), "crypto_tracked_wallets", ["user_id"], unique=False)
    op.create_table(
        "crypto_users",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("alerts_enabled", sa.Boolean(), nullable=True),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("groq_api_key", sa.String(length=200), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "crypto_watchlist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("token_id", sa.String(length=100), nullable=False),
        sa.Column("token_symbol", sa.String(length=20), nullable=False),
        sa.Column("entry_price", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "token_id", name="uix_user_watchlist_token"),
    )
    op.create_index(op.f("ix_crypto_watchlist_user_id"), "crypto_watchlist", ["user_id"], unique=False)
    op.create_table(
        "zenith_ai_conversations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zenith_ai_conversations_user_id"), "zenith_ai_conversations", ["user_id"], unique=False)
    op.create_table(
        "zenith_ai_usage",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("query_count", sa.Integer(), nullable=True),
        sa.Column("summarize_count", sa.Integer(), nullable=True),
        sa.Column("persona", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zenith_ai_usage_user_id"), "zenith_ai_usage", ["user_id"], unique=False)
    op.create_table(
        "zenith_custom_words",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("word", sa.String(length=100), nullable=False),
        sa.Column("added_by", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chat_id", "word", name="_chat_word_uc"),
    )
    op.create_index(op.f("ix_zenith_custom_words_chat_id"), "zenith_custom_words", ["chat_id"], unique=False)
    op.create_table(
        "zenith_group_settings",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("group_name", sa.String(), nullable=True),
        sa.Column("features", sa.String(), nullable=True),
        sa.Column("strength", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("ai_enabled", sa.Boolean(), nullable=True),
        sa.Column("crypto_enabled", sa.Boolean(), nullable=True),
        sa.Column("raid_mode", sa.Boolean(), nullable=True),
        sa.Column("raid_expires_at", sa.DateTime(), nullable=True),
        sa.Column("setup_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_index(op.f("ix_zenith_group_settings_chat_id"), "zenith_group_settings", ["chat_id"], unique=False)
    op.create_table(
        "zenith_group_strikes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("strike_count", sa.Integer(), nullable=True),
        sa.Column("last_violation", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "chat_id", name="_user_chat_uc"),
    )
    op.create_index(op.f("ix_zenith_group_strikes_chat_id"), "zenith_group_strikes", ["chat_id"], unique=False)
    op.create_index(op.f("ix_zenith_group_strikes_user_id"), "zenith_group_strikes", ["user_id"], unique=False)
    op.create_table(
        "zenith_moderation_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("moderator_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zenith_moderation_log_chat_id"), "zenith_moderation_log", ["chat_id"], unique=False)
    op.create_table(
        "zenith_new_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("chat_id", sa.BigInteger(), nullable=True),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "chat_id", name="_new_member_chat_uc"),
    )
    op.create_index(op.f("ix_zenith_new_members_chat_id"), "zenith_new_members", ["chat_id"], unique=False)
    op.create_index(op.f("ix_zenith_new_members_user_id"), "zenith_new_members", ["user_id"], unique=False)
    op.create_table(
        "zenith_scheduled_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("hour", sa.Integer(), nullable=False),
        sa.Column("minute", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("last_sent", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zenith_scheduled_messages_chat_id"), "zenith_scheduled_messages", ["chat_id"], unique=False
    )
    op.create_table(
        "zenith_support_canned",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tag", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tag"),
    )
    op.create_table(
        "zenith_support_faq",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("question", sa.String(length=500), nullable=False),
        sa.Column("answer", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "zenith_support_tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("priority", sa.String(length=20), nullable=True),
        sa.Column("ai_response", sa.Text(), nullable=True),
        sa.Column("admin_response", sa.Text(), nullable=True),
        sa.Column("user_reply", sa.Text(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("last_admin_reply_at", sa.DateTime(), nullable=True),
        sa.Column("user_replied", sa.Boolean(), nullable=True),
        sa.Column("reminder_sent", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_zenith_support_tickets_user_id"), "zenith_support_tickets", ["user_id"], unique=False)
    op.create_table(
        "zenith_welcome_config",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_template", sa.Text(), nullable=False),
        sa.Column("send_dm", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zenith_welcome_config")
    op.drop_index(op.f("ix_zenith_support_tickets_user_id"), table_name="zenith_support_tickets")
    op.drop_table("zenith_support_tickets")
    op.drop_table("zenith_support_faq")
    op.drop_table("zenith_support_canned")
    op.drop_index(op.f("ix_zenith_scheduled_messages_chat_id"), table_name="zenith_scheduled_messages")
    op.drop_table("zenith_scheduled_messages")
    op.drop_index(op.f("ix_zenith_new_members_user_id"), table_name="zenith_new_members")
    op.drop_index(op.f("ix_zenith_new_members_chat_id"), table_name="zenith_new_members")
    op.drop_table("zenith_new_members")
    op.drop_index(op.f("ix_zenith_moderation_log_chat_id"), table_name="zenith_moderation_log")
    op.drop_table("zenith_moderation_log")
    op.drop_index(op.f("ix_zenith_group_strikes_user_id"), table_name="zenith_group_strikes")
    op.drop_index(op.f("ix_zenith_group_strikes_chat_id"), table_name="zenith_group_strikes")
    op.drop_table("zenith_group_strikes")
    op.drop_index(op.f("ix_zenith_group_settings_chat_id"), table_name="zenith_group_settings")
    op.drop_table("zenith_group_settings")
    op.drop_index(op.f("ix_zenith_custom_words_chat_id"), table_name="zenith_custom_words")
    op.drop_table("zenith_custom_words")
    op.drop_index(op.f("ix_zenith_ai_usage_user_id"), table_name="zenith_ai_usage")
    op.drop_table("zenith_ai_usage")
    op.drop_index(op.f("ix_zenith_ai_conversations_user_id"), table_name="zenith_ai_conversations")
    op.drop_table("zenith_ai_conversations")
    op.drop_index(op.f("ix_crypto_watchlist_user_id"), table_name="crypto_watchlist")
    op.drop_table("crypto_watchlist")
    op.drop_table("crypto_users")
    op.drop_index(op.f("ix_crypto_tracked_wallets_user_id"), table_name="crypto_tracked_wallets")
    op.drop_table("crypto_tracked_wallets")
    op.drop_table("crypto_subscriptions")
    op.drop_index(op.f("ix_crypto_saved_audits_user_id"), table_name="crypto_saved_audits")
    op.drop_table("crypto_saved_audits")
    op.drop_index(op.f("ix_crypto_price_alerts_user_id"), table_name="crypto_price_alerts")
    op.drop_table("crypto_price_alerts")
    op.drop_table("crypto_activation_keys")
    op.drop_table("bot_registry")
    op.drop_table("admin_audit_log")
    # ### end Alembic commands ###
